version: 1
camera:
    name: 'Video: http://192.168.8.183:4747/video'
    resolution:
        - 1280
        - 720
intrinsics:
    cameramatrix:
        - - 80000
          - 0
          - 640
        - - 0
          - 80000
          - 360
        - - 0
          - 0
          - 1
    distortioncoeffs:
        - 0
        - 0
        - 0
        - 0
        - 0
    width: 1280
    height: 720
homography:
    - - 0
      - 0
      - 0
    - - 0
      - 0
      - 0
    - - 0
      - 0
      - 0
world_scale: 100
tag_size: 0.15
calibrated_at: "2026-02-06"
